POST http://localhost:3333/api/links
Content-type: application/json

{
  "code": "rocketseat",
  "url": "http://rocketseat.com.br"
}

###

POST http://localhost:3333/api/links
Content-type: application/json

{
  "code": "rocketseat",
  "url": "http://rocketseat.com.br"
}

###

GET http://localhost:3333/api/links


### 

GET http://localhost:3333/google

### 

GET http://localhost:3333/api/metrics